# A list of devices you want to take the screenshots from
devices([
  "iPhone 6",
  "iPhone 6 Plus",
  "iPhone 5",
  "iPhone 4s",
  "iPad Air",
  "iPad Pro"
])

languages([
  "de-DE", 
  "en-US", 
  "es-ES", 
  "fr-FR", 
  "it-IT", 
  "ja-JP", 
  "ko-KR", 
  "nl-NL", 
  "ru-RU", 
  "sv-SE", 
  "cmn-Hans"
])

# The name of the project's scheme
scheme 'MindNode for iOS'

# Where is your project (or workspace)? Provide the full path here
project '../MindNode-iOS.xcworkspace'
